name: hassanallamportalflutter
description: HassanAllamPortalFlutter

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

  #Media libiraries
  swipe_image_gallery: ^0.5.1
  video_player: ^2.4.4
  cached_network_image: ^3.2.1
  card_swiper: ^2.0.4
  full_screen_image_null_safe: any


  #design libiraries
  heroicons: ^0.5.0 #this is responsible for angular icons as the icons assets are in this libirary
  shimmer: ^2.0.0
  entry: ^0.0.6
  sprung: ^3.0.0
  delayed_display: ^2.0.0
  page_transition: ^2.0.5
  conditional_builder_null_safety: ^0.0.6
  badges: ^2.0.2
  multi_select_flutter: ^4.1.2
  flutter_multiselect: ^1.0.0
  sizer: ^2.0.15
  flutter_svg: ^1.1.0
  flutter_polls: ^0.0.6
  circular: ^0.0.5
  dropdown_search: ^5.0.2
  percent_indicator: ^4.0.1
#  grouped_list: ^5.1.2 /// unused so far
  simple_grouped_listview: ^1.0.1

  #Animation libiraries
  animated_splash_screen: ^1.2.0
  animations: ^2.0.2
  rounded_loading_button: ^2.0.8

  #Text libiraries
  animated_text_kit: ^4.2.2

  #Web libiraries
  flutter_html: any
  http: any
  html: ^0.15.0
  firebase_core: ^1.20.0
  firebase_auth: ^3.6.2
  firebase_database: ^9.1.0
  firebase_crashlytics: ^2.8.6
  dio: ^4.0.6
  url_launcher: ^6.1.2

  #Bloc libiraries
  flutter_bloc: any
  hydrated_bloc: any
  bloc: any
  connectivity_plus: any

  # QR code
  qr_flutter: ^4.0.0
  vcard_maintained: any

  #functionality helper
  formz: ^0.4.1
  device_info: ^2.0.3
  path: ^1.8.1
  flutter_local_notifications: ^9.6.0
  path_provider: ^2.0.11
  flutter_downloader: ^1.7.4
  equatable: any
  flutter_form_builder: ^7.2.0
  permission_handler: ^9.2.0
  open_file: ^3.2.1
  file_picker: ^4.6.1
  package_info_plus: ^1.4.2
  flutter_easyloading: ^3.0.5


#repositories
  authentication_repository:
    path: packages/authentication_repository



#  flutter_native_splash: any
#flutter_native_splash:
#    background_image: assets/images/native_splash.png
#    fullscreen: false
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1
  json_serializable: any
  build_runner: ^2.1.11
  flutter_web_browser: ^0.17.1
  flutter_gen_runner: ^4.3.0


lutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80   # Optional (default: 80)

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true

  assets:
    enabled: true
    package_parameter_enabled: false
    # Assets.imagesChip
    # style: camel-case

    # Assets.images_chip
    # style: snake-case

    # Assets.images.chip (default style)
    # style: dot-delimiter

  fonts:
    enabled: true


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/images/buildings.png
    - assets/images/fulllogoblue.png
    - assets/images/backgroundattendance.jpg
    - assets/images/login_image_background.png
    - assets/images/login_image_background_two.png
    - assets/images/login_image_buildings.png
    - assets/images/login_image_light.png
    - assets/images/login_image_logo.png
    - assets/images/Builds.png
    - assets/images/native_splash.png
    - assets/images/S_Background.png
    - assets/images/home_cropped.jpg
    - assets/images/Benefits.png
    - assets/images/Media.png
    - assets/images/Subsidiaries.png
    - assets/images/Values.png
    - assets/images/Cover.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: RobotoFlex
       fonts:
         - asset: assets/fonts/RobotoFlex-Regular.ttf
     - family: RobotoCondensed
       fonts:
         - asset: assets/fonts/RobotoCondensed-Regular.ttf
         - asset: assets/fonts/RobotoCondensed-Light.ttf
         - asset: assets/fonts/RobotoCondensed-Bold.ttf
           weight: 700
         - asset: assets/fonts/RobotoCondensed-Italic.ttf
           style: italic
     - family: Nunito
       fonts:
         - asset: assets/fonts/NunitoBold.ttf

     - family: AquinoDemo
       fonts:
         - asset: assets/fonts/AquinoDemo.ttf

     - family: Nisebuschgardens
       fonts:
         - asset: assets/fonts/Nisebuschgardens.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
