name: authentication_repository
description: Dart package which manages the authentication domain.
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: any
  equatable: ^2.0.3
  shared_preferences: ^2.0.13
  firebase_core: ^1.15.0
  firebase_auth: ^3.3.15
  firebase_messaging: ^11.3.0
  device_info: ^2.0.3
  firebase_database: ^9.0.13
