// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 118.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************
class Assets {
  static const String package = 'hassanallamportalflutter';

  static const String assets_images_Benefits_png = 'assets/images/Benefits.png';
  static const String hassanallamportalflutter$assets_images_Benefits_png = 'packages/hassanallamportalflutter/assets/images/Benefits.png';

  static const String assets_images_Builds_png = 'assets/images/Builds.png';
  static const String hassanallamportalflutter$assets_images_Builds_png = 'packages/hassanallamportalflutter/assets/images/Builds.png';

  static const String assets_images_Cover_png = 'assets/images/Cover.png';
  static const String hassanallamportalflutter$assets_images_Cover_png = 'packages/hassanallamportalflutter/assets/images/Cover.png';

  static const String assets_images_Media_png = 'assets/images/Media.png';
  static const String hassanallamportalflutter$assets_images_Media_png = 'packages/hassanallamportalflutter/assets/images/Media.png';

  static const String assets_images_S_Background_png = 'assets/images/S_Background.png';
  static const String hassanallamportalflutter$assets_images_S_Background_png = 'packages/hassanallamportalflutter/assets/images/S_Background.png';

  static const String assets_images_Subsidiaries_png = 'assets/images/Subsidiaries.png';
  static const String hassanallamportalflutter$assets_images_Subsidiaries_png = 'packages/hassanallamportalflutter/assets/images/Subsidiaries.png';

  static const String assets_images_Values_png = 'assets/images/Values.png';
  static const String hassanallamportalflutter$assets_images_Values_png = 'packages/hassanallamportalflutter/assets/images/Values.png';

  static const String assets_images_backgroundattendance_jpg = 'assets/images/backgroundattendance.jpg';
  static const String hassanallamportalflutter$assets_images_backgroundattendance_jpg = 'packages/hassanallamportalflutter/assets/images/backgroundattendance.jpg';

  static const String assets_images_backgroundcatalogpattern_png = 'assets/images/backgroundcatalogpattern.png';
  static const String hassanallamportalflutter$assets_images_backgroundcatalogpattern_png = 'packages/hassanallamportalflutter/assets/images/backgroundcatalogpattern.png';

  static const String assets_images_bot6_jpg = 'assets/images/bot6.jpg';
  static const String hassanallamportalflutter$assets_images_bot6_jpg = 'packages/hassanallamportalflutter/assets/images/bot6.jpg';

  static const String assets_images_buildings_png = 'assets/images/buildings.png';
  static const String hassanallamportalflutter$assets_images_buildings_png = 'packages/hassanallamportalflutter/assets/images/buildings.png';

  static const String assets_images_catlogo_png = 'assets/images/catlogo.png';
  static const String hassanallamportalflutter$assets_images_catlogo_png = 'packages/hassanallamportalflutter/assets/images/catlogo.png';

  static const String assets_images_catlogoone_png = 'assets/images/catlogoone.png';
  static const String hassanallamportalflutter$assets_images_catlogoone_png = 'packages/hassanallamportalflutter/assets/images/catlogoone.png';

  static const String assets_images_catlogothree_png = 'assets/images/catlogothree.png';
  static const String hassanallamportalflutter$assets_images_catlogothree_png = 'packages/hassanallamportalflutter/assets/images/catlogothree.png';

  static const String assets_images_catlogotwo_png = 'assets/images/catlogotwo.png';
  static const String hassanallamportalflutter$assets_images_catlogotwo_png = 'packages/hassanallamportalflutter/assets/images/catlogotwo.png';

  static const String assets_images_defaultBg_jpg = 'assets/images/defaultBg.jpg';
  static const String hassanallamportalflutter$assets_images_defaultBg_jpg = 'packages/hassanallamportalflutter/assets/images/defaultBg.jpg';

  static const String assets_images_favicon_png = 'assets/images/favicon.png';
  static const String hassanallamportalflutter$assets_images_favicon_png = 'packages/hassanallamportalflutter/assets/images/favicon.png';

  static const String assets_images_fulllogoblue_png = 'assets/images/fulllogoblue.png';
  static const String hassanallamportalflutter$assets_images_fulllogoblue_png = 'packages/hassanallamportalflutter/assets/images/fulllogoblue.png';

  static const String assets_images_home_cropped_jpg = 'assets/images/home_cropped.jpg';
  static const String hassanallamportalflutter$assets_images_home_cropped_jpg = 'packages/hassanallamportalflutter/assets/images/home_cropped.jpg';

  static const String assets_images_homepage_attendanceIcon_png = 'assets/images/homepage/attendanceIcon.png';
  static const String hassanallamportalflutter$assets_images_homepage_attendanceIcon_png = 'packages/hassanallamportalflutter/assets/images/homepage/attendanceIcon.png';

  static const String assets_images_homepage_benefitsIcon_png = 'assets/images/homepage/benefitsIcon.png';
  static const String hassanallamportalflutter$assets_images_homepage_benefitsIcon_png = 'packages/hassanallamportalflutter/assets/images/homepage/benefitsIcon.png';

  static const String assets_images_homepage_contactListIcon_png = 'assets/images/homepage/contactListIcon.png';
  static const String hassanallamportalflutter$assets_images_homepage_contactListIcon_png = 'packages/hassanallamportalflutter/assets/images/homepage/contactListIcon.png';

  static const String assets_images_homepage_economyNewsIcon_png = 'assets/images/homepage/economyNewsIcon.png';
  static const String hassanallamportalflutter$assets_images_homepage_economyNewsIcon_png = 'packages/hassanallamportalflutter/assets/images/homepage/economyNewsIcon.png';

  static const String assets_images_homepage_haNewsLetterIcon_png = 'assets/images/homepage/haNewsLetterIcon.png';
  static const String hassanallamportalflutter$assets_images_homepage_haNewsLetterIcon_png = 'packages/hassanallamportalflutter/assets/images/homepage/haNewsLetterIcon.png';

  static const String assets_images_homepage_hrRequestsIcon_png = 'assets/images/homepage/hrRequestsIcon.png';
  static const String hassanallamportalflutter$assets_images_homepage_hrRequestsIcon_png = 'packages/hassanallamportalflutter/assets/images/homepage/hrRequestsIcon.png';

  static const String assets_images_homepage_itRequestIcon_png = 'assets/images/homepage/itRequestIcon.png';
  static const String hassanallamportalflutter$assets_images_homepage_itRequestIcon_png = 'packages/hassanallamportalflutter/assets/images/homepage/itRequestIcon.png';

  static const String assets_images_homepage_mediaCenterIcon_png = 'assets/images/homepage/mediaCenterIcon.png';
  static const String hassanallamportalflutter$assets_images_homepage_mediaCenterIcon_png = 'packages/hassanallamportalflutter/assets/images/homepage/mediaCenterIcon.png';

  static const String assets_images_homepage_newsIcon_png = 'assets/images/homepage/newsIcon.png';
  static const String hassanallamportalflutter$assets_images_homepage_newsIcon_png = 'packages/hassanallamportalflutter/assets/images/homepage/newsIcon.png';

  static const String assets_images_homepage_staffDashboardIcon_png = 'assets/images/homepage/staffDashboardIcon.png';
  static const String hassanallamportalflutter$assets_images_homepage_staffDashboardIcon_png = 'packages/hassanallamportalflutter/assets/images/homepage/staffDashboardIcon.png';

  static const String assets_images_login_image_background_png = 'assets/images/login_image_background.png';
  static const String hassanallamportalflutter$assets_images_login_image_background_png = 'packages/hassanallamportalflutter/assets/images/login_image_background.png';

  static const String assets_images_login_image_background_two_png = 'assets/images/login_image_background_two.png';
  static const String hassanallamportalflutter$assets_images_login_image_background_two_png = 'packages/hassanallamportalflutter/assets/images/login_image_background_two.png';

  static const String assets_images_login_image_buildings_png = 'assets/images/login_image_buildings.png';
  static const String hassanallamportalflutter$assets_images_login_image_buildings_png = 'packages/hassanallamportalflutter/assets/images/login_image_buildings.png';

  static const String assets_images_login_image_light_png = 'assets/images/login_image_light.png';
  static const String hassanallamportalflutter$assets_images_login_image_light_png = 'packages/hassanallamportalflutter/assets/images/login_image_light.png';

  static const String assets_images_login_image_logo_png = 'assets/images/login_image_logo.png';
  static const String hassanallamportalflutter$assets_images_login_image_logo_png = 'packages/hassanallamportalflutter/assets/images/login_image_logo.png';

  static const String assets_images_logo_png = 'assets/images/logo.png';
  static const String hassanallamportalflutter$assets_images_logo_png = 'packages/hassanallamportalflutter/assets/images/logo.png';

  static const String assets_images_native_splash_png = 'assets/images/native_splash.png';
  static const String hassanallamportalflutter$assets_images_native_splash_png = 'packages/hassanallamportalflutter/assets/images/native_splash.png';

  static const String assets_images_no_data_found_png = 'assets/images/no_data_found.png';
  static const String hassanallamportalflutter$assets_images_no_data_found_png = 'packages/hassanallamportalflutter/assets/images/no_data_found.png';

  static const String assets_images_no_search_icon_png = 'assets/images/no_search_icon.png';
  static const String hassanallamportalflutter$assets_images_no_search_icon_png = 'packages/hassanallamportalflutter/assets/images/no_search_icon.png';

  static const String assets_images_staffdashboard_arrowdown_png = 'assets/images/staffdashboard/arrowdown.png';
  static const String hassanallamportalflutter$assets_images_staffdashboard_arrowdown_png = 'packages/hassanallamportalflutter/assets/images/staffdashboard/arrowdown.png';

  static const String assets_images_staffdashboard_boxlayer_png = 'assets/images/staffdashboard/boxlayer.png';
  static const String hassanallamportalflutter$assets_images_staffdashboard_boxlayer_png = 'packages/hassanallamportalflutter/assets/images/staffdashboard/boxlayer.png';

  static const String assets_images_staffdashboard_dashboard1_png = 'assets/images/staffdashboard/dashboard1.png';
  static const String hassanallamportalflutter$assets_images_staffdashboard_dashboard1_png = 'packages/hassanallamportalflutter/assets/images/staffdashboard/dashboard1.png';

  static const String assets_images_staffdashboard_dashboard2_png = 'assets/images/staffdashboard/dashboard2.png';
  static const String hassanallamportalflutter$assets_images_staffdashboard_dashboard2_png = 'packages/hassanallamportalflutter/assets/images/staffdashboard/dashboard2.png';

  static const String assets_images_staffdashboard_dashboard3_jpg = 'assets/images/staffdashboard/dashboard3.jpg';
  static const String hassanallamportalflutter$assets_images_staffdashboard_dashboard3_jpg = 'packages/hassanallamportalflutter/assets/images/staffdashboard/dashboard3.jpg';

  static const String assets_images_staffdashboard_dashboardbgsub_jpg = 'assets/images/staffdashboard/dashboardbgsub.jpg';
  static const String hassanallamportalflutter$assets_images_staffdashboard_dashboardbgsub_jpg = 'packages/hassanallamportalflutter/assets/images/staffdashboard/dashboardbgsub.jpg';

  static const String assets_images_staffdashboard_dashboardicon_png = 'assets/images/staffdashboard/dashboardicon.png';
  static const String hassanallamportalflutter$assets_images_staffdashboard_dashboardicon_png = 'packages/hassanallamportalflutter/assets/images/staffdashboard/dashboardicon.png';

  static const String assets_images_staffdashboard_dashboardsub1_png = 'assets/images/staffdashboard/dashboardsub1.png';
  static const String hassanallamportalflutter$assets_images_staffdashboard_dashboardsub1_png = 'packages/hassanallamportalflutter/assets/images/staffdashboard/dashboardsub1.png';

  static const String assets_images_staffdashboard_dashboardsub2_png = 'assets/images/staffdashboard/dashboardsub2.png';
  static const String hassanallamportalflutter$assets_images_staffdashboard_dashboardsub2_png = 'packages/hassanallamportalflutter/assets/images/staffdashboard/dashboardsub2.png';

  static const String assets_images_staffdashboard_dashboardsub3_png = 'assets/images/staffdashboard/dashboardsub3.png';
  static const String hassanallamportalflutter$assets_images_staffdashboard_dashboardsub3_png = 'packages/hassanallamportalflutter/assets/images/staffdashboard/dashboardsub3.png';

  static const String assets_images_staffdashboard_dashboardsub4_png = 'assets/images/staffdashboard/dashboardsub4.png';
  static const String hassanallamportalflutter$assets_images_staffdashboard_dashboardsub4_png = 'packages/hassanallamportalflutter/assets/images/staffdashboard/dashboardsub4.png';

  static const String assets_images_staffdashboard_empicon_png = 'assets/images/staffdashboard/empicon.png';
  static const String hassanallamportalflutter$assets_images_staffdashboard_empicon_png = 'packages/hassanallamportalflutter/assets/images/staffdashboard/empicon.png';

  static const String assets_images_staffdashboard_labor_png = 'assets/images/staffdashboard/labor.png';
  static const String hassanallamportalflutter$assets_images_staffdashboard_labor_png = 'packages/hassanallamportalflutter/assets/images/staffdashboard/labor.png';

  static const String assets_images_staffdashboard_laborbox_png = 'assets/images/staffdashboard/laborbox.png';
  static const String hassanallamportalflutter$assets_images_staffdashboard_laborbox_png = 'packages/hassanallamportalflutter/assets/images/staffdashboard/laborbox.png';

  static const String assets_images_staffdashboard_laboreffect_png = 'assets/images/staffdashboard/laboreffect.png';
  static const String hassanallamportalflutter$assets_images_staffdashboard_laboreffect_png = 'packages/hassanallamportalflutter/assets/images/staffdashboard/laboreffect.png';

  static const String assets_images_staffdashboard_laboricon_png = 'assets/images/staffdashboard/laboricon.png';
  static const String hassanallamportalflutter$assets_images_staffdashboard_laboricon_png = 'packages/hassanallamportalflutter/assets/images/staffdashboard/laboricon.png';

  static const String assets_images_staffdashboard_staffbox_png = 'assets/images/staffdashboard/staffbox.png';
  static const String hassanallamportalflutter$assets_images_staffdashboard_staffbox_png = 'packages/hassanallamportalflutter/assets/images/staffdashboard/staffbox.png';

  static const String assets_images_staffdashboard_staffeffect_png = 'assets/images/staffdashboard/staffeffect.png';
  static const String hassanallamportalflutter$assets_images_staffdashboard_staffeffect_png = 'packages/hassanallamportalflutter/assets/images/staffdashboard/staffeffect.png';

  static const String assets_images_welcomeImage_gif = 'assets/images/welcomeImage.gif';
  static const String hassanallamportalflutter$assets_images_welcomeImage_gif = 'packages/hassanallamportalflutter/assets/images/welcomeImage.gif';


  //TODO SHOW ERROR THAT THE FOLLOWING IMAGES IS ARLEADY DEFIND

  // static const String assets\images\Benefits_png = 'assets\images\Benefits.png';
  // static const String hassanallamportalflutter$assets\images\Benefits_png = 'packages/hassanallamportalflutter/assets\images\Benefits.png';
  //
  // static const String assets\images\Builds_png = 'assets\images\Builds.png';
  // static const String hassanallamportalflutter$assets\images\Builds_png = 'packages/hassanallamportalflutter/assets\images\Builds.png';
  //
  // static const String assets\images\Cover_png = 'assets\images\Cover.png';
  // static const String hassanallamportalflutter$assets\images\Cover_png = 'packages/hassanallamportalflutter/assets\images\Cover.png';
  //
  // static const String assets\images\MainBackground_jpg = 'assets\images\MainBackground.jpg';
  // static const String hassanallamportalflutter$assets\images\MainBackground_jpg = 'packages/hassanallamportalflutter/assets\images\MainBackground.jpg';
  //
  // static const String assets\images\Media_png = 'assets\images\Media.png';
  // static const String hassanallamportalflutter$assets\images\Media_png = 'packages/hassanallamportalflutter/assets\images\Media.png';
  //
  // static const String assets\images\S_Background_png = 'assets\images\S_Background.png';
  // static const String hassanallamportalflutter$assets\images\S_Background_png = 'packages/hassanallamportalflutter/assets\images\S_Background.png';
  //
  // static const String assets\images\Subsidiaries_png = 'assets\images\Subsidiaries.png';
  // static const String hassanallamportalflutter$assets\images\Subsidiaries_png = 'packages/hassanallamportalflutter/assets\images\Subsidiaries.png';
  //
  // static const String assets\images\Values_png = 'assets\images\Values.png';
  // static const String hassanallamportalflutter$assets\images\Values_png = 'packages/hassanallamportalflutter/assets\images\Values.png';
  //
  // static const String assets\images\backgroundattendance_jpg = 'assets\images\backgroundattendance.jpg';
  // static const String hassanallamportalflutter$assets\images\backgroundattendance_jpg = 'packages/hassanallamportalflutter/assets\images\backgroundattendance.jpg';
  //
  // static const String assets\images\backgroundcatalogpattern_png = 'assets\images\backgroundcatalogpattern.png';
  // static const String hassanallamportalflutter$assets\images\backgroundcatalogpattern_png = 'packages/hassanallamportalflutter/assets\images\backgroundcatalogpattern.png';
  //
  // static const String assets\images\bot6_jpg = 'assets\images\bot6.jpg';
  // static const String hassanallamportalflutter$assets\images\bot6_jpg = 'packages/hassanallamportalflutter/assets\images\bot6.jpg';
  //
  // static const String assets\images\buildings_png = 'assets\images\buildings.png';
  // static const String hassanallamportalflutter$assets\images\buildings_png = 'packages/hassanallamportalflutter/assets\images\buildings.png';
  //
  // static const String assets\images\catlogo_png = 'assets\images\catlogo.png';
  // static const String hassanallamportalflutter$assets\images\catlogo_png = 'packages/hassanallamportalflutter/assets\images\catlogo.png';
  //
  // static const String assets\images\catlogoone_png = 'assets\images\catlogoone.png';
  // static const String hassanallamportalflutter$assets\images\catlogoone_png = 'packages/hassanallamportalflutter/assets\images\catlogoone.png';
  //
  // static const String assets\images\catlogothree_png = 'assets\images\catlogothree.png';
  // static const String hassanallamportalflutter$assets\images\catlogothree_png = 'packages/hassanallamportalflutter/assets\images\catlogothree.png';
  //
  // static const String assets\images\catlogotwo_png = 'assets\images\catlogotwo.png';
  // static const String hassanallamportalflutter$assets\images\catlogotwo_png = 'packages/hassanallamportalflutter/assets\images\catlogotwo.png';
  //
  // static const String assets\images\defaultBg_jpg = 'assets\images\defaultBg.jpg';
  // static const String hassanallamportalflutter$assets\images\defaultBg_jpg = 'packages/hassanallamportalflutter/assets\images\defaultBg.jpg';
  //
  // static const String assets\images\excel_png = 'assets\images\excel.png';
  // static const String hassanallamportalflutter$assets\images\excel_png = 'packages/hassanallamportalflutter/assets\images\excel.png';
  //
  // static const String assets\images\favicon_png = 'assets\images\favicon.png';
  // static const String hassanallamportalflutter$assets\images\favicon_png = 'packages/hassanallamportalflutter/assets\images\favicon.png';
  //
  // static const String assets\images\fulllogoblue_png = 'assets\images\fulllogoblue.png';
  // static const String hassanallamportalflutter$assets\images\fulllogoblue_png = 'packages/hassanallamportalflutter/assets\images\fulllogoblue.png';
  //
  // static const String assets\images\home_cropped_jpg = 'assets\images\home_cropped.jpg';
  // static const String hassanallamportalflutter$assets\images\home_cropped_jpg = 'packages/hassanallamportalflutter/assets\images\home_cropped.jpg';
  //
  // static const String assets\images\homepage\attendanceIcon_png = 'assets\images\homepage\attendanceIcon.png';
  // static const String hassanallamportalflutter$assets\images\homepage\attendanceIcon_png = 'packages/hassanallamportalflutter/assets\images\homepage\attendanceIcon.png';
  //
  // static const String assets\images\homepage\benefitsIcon_png = 'assets\images\homepage\benefitsIcon.png';
  // static const String hassanallamportalflutter$assets\images\homepage\benefitsIcon_png = 'packages/hassanallamportalflutter/assets\images\homepage\benefitsIcon.png';
  //
  // static const String assets\images\homepage\contactListIcon_png = 'assets\images\homepage\contactListIcon.png';
  // static const String hassanallamportalflutter$assets\images\homepage\contactListIcon_png = 'packages/hassanallamportalflutter/assets\images\homepage\contactListIcon.png';
  //
  // static const String assets\images\homepage\economyNewsIcon_png = 'assets\images\homepage\economyNewsIcon.png';
  // static const String hassanallamportalflutter$assets\images\homepage\economyNewsIcon_png = 'packages/hassanallamportalflutter/assets\images\homepage\economyNewsIcon.png';
  //
  // static const String assets\images\homepage\haNewsLetterIcon_png = 'assets\images\homepage\haNewsLetterIcon.png';
  // static const String hassanallamportalflutter$assets\images\homepage\haNewsLetterIcon_png = 'packages/hassanallamportalflutter/assets\images\homepage\haNewsLetterIcon.png';
  //
  // static const String assets\images\homepage\hrRequestsIcon_png = 'assets\images\homepage\hrRequestsIcon.png';
  // static const String hassanallamportalflutter$assets\images\homepage\hrRequestsIcon_png = 'packages/hassanallamportalflutter/assets\images\homepage\hrRequestsIcon.png';
  //
  // static const String assets\images\homepage\itRequestIcon_png = 'assets\images\homepage\itRequestIcon.png';
  // static const String hassanallamportalflutter$assets\images\homepage\itRequestIcon_png = 'packages/hassanallamportalflutter/assets\images\homepage\itRequestIcon.png';
  //
  // static const String assets\images\homepage\mediaCenterIcon_png = 'assets\images\homepage\mediaCenterIcon.png';
  // static const String hassanallamportalflutter$assets\images\homepage\mediaCenterIcon_png = 'packages/hassanallamportalflutter/assets\images\homepage\mediaCenterIcon.png';
  //
  // static const String assets\images\homepage\newsIcon_png = 'assets\images\homepage\newsIcon.png';
  // static const String hassanallamportalflutter$assets\images\homepage\newsIcon_png = 'packages/hassanallamportalflutter/assets\images\homepage\newsIcon.png';
  //
  // static const String assets\images\homepage\staffDashboardIcon_png = 'assets\images\homepage\staffDashboardIcon.png';
  // static const String hassanallamportalflutter$assets\images\homepage\staffDashboardIcon_png = 'packages/hassanallamportalflutter/assets\images\homepage\staffDashboardIcon.png';
  //
  // static const String assets\images\login_image_background_png = 'assets\images\login_image_background.png';
  // static const String hassanallamportalflutter$assets\images\login_image_background_png = 'packages/hassanallamportalflutter/assets\images\login_image_background.png';
  //
  // static const String assets\images\login_image_background_two_png = 'assets\images\login_image_background_two.png';
  // static const String hassanallamportalflutter$assets\images\login_image_background_two_png = 'packages/hassanallamportalflutter/assets\images\login_image_background_two.png';
  //
  // static const String assets\images\login_image_buildings_png = 'assets\images\login_image_buildings.png';
  // static const String hassanallamportalflutter$assets\images\login_image_buildings_png = 'packages/hassanallamportalflutter/assets\images\login_image_buildings.png';
  //
  // static const String assets\images\login_image_light_png = 'assets\images\login_image_light.png';
  // static const String hassanallamportalflutter$assets\images\login_image_light_png = 'packages/hassanallamportalflutter/assets\images\login_image_light.png';
  //
  // static const String assets\images\login_image_logo_png = 'assets\images\login_image_logo.png';
  // static const String hassanallamportalflutter$assets\images\login_image_logo_png = 'packages/hassanallamportalflutter/assets\images\login_image_logo.png';
  //
  // static const String assets\images\logo_png = 'assets\images\logo.png';
  // static const String hassanallamportalflutter$assets\images\logo_png = 'packages/hassanallamportalflutter/assets\images\logo.png';
  //
  // static const String assets\images\native_splash_png = 'assets\images\native_splash.png';
  // static const String hassanallamportalflutter$assets\images\native_splash_png = 'packages/hassanallamportalflutter/assets\images\native_splash.png';
  //
  // static const String assets\images\no_data_found_png = 'assets\images\no_data_found.png';
  // static const String hassanallamportalflutter$assets\images\no_data_found_png = 'packages/hassanallamportalflutter/assets\images\no_data_found.png';
  //
  // static const String assets\images\no_search_icon_png = 'assets\images\no_search_icon.png';
  // static const String hassanallamportalflutter$assets\images\no_search_icon_png = 'packages/hassanallamportalflutter/assets\images\no_search_icon.png';
  //
  // static const String assets\images\outlook_png = 'assets\images\outlook.png';
  // static const String hassanallamportalflutter$assets\images\outlook_png = 'packages/hassanallamportalflutter/assets\images\outlook.png';
  //
  // static const String assets\images\staffdashboard\arrowdown_png = 'assets\images\staffdashboard\arrowdown.png';
  // static const String hassanallamportalflutter$assets\images\staffdashboard\arrowdown_png = 'packages/hassanallamportalflutter/assets\images\staffdashboard\arrowdown.png';
  //
  // static const String assets\images\staffdashboard\boxlayer_png = 'assets\images\staffdashboard\boxlayer.png';
  // static const String hassanallamportalflutter$assets\images\staffdashboard\boxlayer_png = 'packages/hassanallamportalflutter/assets\images\staffdashboard\boxlayer.png';
  //
  // static const String assets\images\staffdashboard\dashboard1_png = 'assets\images\staffdashboard\dashboard1.png';
  // static const String hassanallamportalflutter$assets\images\staffdashboard\dashboard1_png = 'packages/hassanallamportalflutter/assets\images\staffdashboard\dashboard1.png';
  //
  // static const String assets\images\staffdashboard\dashboard2_png = 'assets\images\staffdashboard\dashboard2.png';
  // static const String hassanallamportalflutter$assets\images\staffdashboard\dashboard2_png = 'packages/hassanallamportalflutter/assets\images\staffdashboard\dashboard2.png';
  //
  // static const String assets\images\staffdashboard\dashboard3_jpg = 'assets\images\staffdashboard\dashboard3.jpg';
  // static const String hassanallamportalflutter$assets\images\staffdashboard\dashboard3_jpg = 'packages/hassanallamportalflutter/assets\images\staffdashboard\dashboard3.jpg';
  //
  // static const String assets\images\staffdashboard\dashboardbgsub_jpg = 'assets\images\staffdashboard\dashboardbgsub.jpg';
  // static const String hassanallamportalflutter$assets\images\staffdashboard\dashboardbgsub_jpg = 'packages/hassanallamportalflutter/assets\images\staffdashboard\dashboardbgsub.jpg';
  //
  // static const String assets\images\staffdashboard\dashboardicon_png = 'assets\images\staffdashboard\dashboardicon.png';
  // static const String hassanallamportalflutter$assets\images\staffdashboard\dashboardicon_png = 'packages/hassanallamportalflutter/assets\images\staffdashboard\dashboardicon.png';
  //
  // static const String assets\images\staffdashboard\dashboardsub1_png = 'assets\images\staffdashboard\dashboardsub1.png';
  // static const String hassanallamportalflutter$assets\images\staffdashboard\dashboardsub1_png = 'packages/hassanallamportalflutter/assets\images\staffdashboard\dashboardsub1.png';
  //
  // static const String assets\images\staffdashboard\dashboardsub2_png = 'assets\images\staffdashboard\dashboardsub2.png';
  // static const String hassanallamportalflutter$assets\images\staffdashboard\dashboardsub2_png = 'packages/hassanallamportalflutter/assets\images\staffdashboard\dashboardsub2.png';
  //
  // static const String assets\images\staffdashboard\dashboardsub3_png = 'assets\images\staffdashboard\dashboardsub3.png';
  // static const String hassanallamportalflutter$assets\images\staffdashboard\dashboardsub3_png = 'packages/hassanallamportalflutter/assets\images\staffdashboard\dashboardsub3.png';
  //
  // static const String assets\images\staffdashboard\dashboardsub4_png = 'assets\images\staffdashboard\dashboardsub4.png';
  // static const String hassanallamportalflutter$assets\images\staffdashboard\dashboardsub4_png = 'packages/hassanallamportalflutter/assets\images\staffdashboard\dashboardsub4.png';
  //
  // static const String assets\images\staffdashboard\empicon_png = 'assets\images\staffdashboard\empicon.png';
  // static const String hassanallamportalflutter$assets\images\staffdashboard\empicon_png = 'packages/hassanallamportalflutter/assets\images\staffdashboard\empicon.png';
  //
  // static const String assets\images\staffdashboard\employee_png = 'assets\images\staffdashboard\employee.png';
  // static const String hassanallamportalflutter$assets\images\staffdashboard\employee_png = 'packages/hassanallamportalflutter/assets\images\staffdashboard\employee.png';
  //
  // static const String assets\images\staffdashboard\labor_png = 'assets\images\staffdashboard\labor.png';
  // static const String hassanallamportalflutter$assets\images\staffdashboard\labor_png = 'packages/hassanallamportalflutter/assets\images\staffdashboard\labor.png';
  //
  // static const String assets\images\staffdashboard\laborbox_png = 'assets\images\staffdashboard\laborbox.png';
  // static const String hassanallamportalflutter$assets\images\staffdashboard\laborbox_png = 'packages/hassanallamportalflutter/assets\images\staffdashboard\laborbox.png';
  //
  // static const String assets\images\staffdashboard\laboreffect_png = 'assets\images\staffdashboard\laboreffect.png';
  // static const String hassanallamportalflutter$assets\images\staffdashboard\laboreffect_png = 'packages/hassanallamportalflutter/assets\images\staffdashboard\laboreffect.png';
  //
  // static const String assets\images\staffdashboard\laboricon_png = 'assets\images\staffdashboard\laboricon.png';
  // static const String hassanallamportalflutter$assets\images\staffdashboard\laboricon_png = 'packages/hassanallamportalflutter/assets\images\staffdashboard\laboricon.png';
  //
  // static const String assets\images\staffdashboard\staffbox_png = 'assets\images\staffdashboard\staffbox.png';
  // static const String hassanallamportalflutter$assets\images\staffdashboard\staffbox_png = 'packages/hassanallamportalflutter/assets\images\staffdashboard\staffbox.png';
  //
  // static const String assets\images\staffdashboard\staffeffect_png = 'assets\images\staffdashboard\staffeffect.png';
  // static const String hassanallamportalflutter$assets\images\staffdashboard\staffeffect_png = 'packages/hassanallamportalflutter/assets\images\staffdashboard\staffeffect.png';
  //
  // static const String assets\images\welcomeImage_gif = 'assets\images\welcomeImage.gif';
  // static const String hassanallamportalflutter$assets\images\welcomeImage_gif = 'packages/hassanallamportalflutter/assets\images\welcomeImage.gif';
}
