// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxteIUtdpYN1RRQwnClOZrVK0Gi0XEZLI',
    appId: '1:403496742640:android:b41c6dfc83eacc57915c35',
    messagingSenderId: '403496742640',
    projectId: 'hassanallamportal-11076',
    databaseURL: 'https://hassanallamportal-11076-default-rtdb.firebaseio.com',
    storageBucket: 'hassanallamportal-11076.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY1iVTwA3EDYowU9_BS-VjYBJ1QjHLqB0',
    appId: '1:403496742640:ios:43fee71f6e99d04f915c35',
    messagingSenderId: '403496742640',
    projectId: 'hassanallamportal-11076',
    databaseURL: 'https://hassanallamportal-11076-default-rtdb.firebaseio.com',
    storageBucket: 'hassanallamportal-11076.appspot.com',
    androidClientId: '403496742640-k9feo7q6l20sgc6hpllv3l36vteusuao.apps.googleusercontent.com',
    iosClientId: '403496742640-p9efl4lqb24rcsmitp8lq923r0i271gi.apps.googleusercontent.com',
    iosBundleId: 'com.hassanallam.hassanallamportalflutter',
  );
}
